theme = "dracula_at_night"

[editor]
mouse = true
bufferline = "multiple"
auto-pairs = false

[editor.statusline]
left = ["spinner", "file-name", "total-line-numbers", "position", "file-encoding"]
center = ["mode"]
right = ["selections", "primary-selection-length", "file-type", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false

[keys.normal]
p = "paste_clipboard_before"
y = "yank_main_selection_to_clipboard"
esc = ["collapse_selection", "keep_primary_selection"]
