theme = "new_moon"

[editor]
mouse = true
bufferline = "multiple"
auto-pairs = true

[editor.statusline]
left = ["spinner", "file-name", "total-line-numbers", "position", "file-encoding"]
center = ["mode"]
right = ["selections", "primary-selection-length", "file-type", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-inlay-hints = false

[editor.file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
p = "paste_clipboard_before"
