name: Mirror Sourcehut Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mercurial git python3 rsync
          git clone https://github.com/frej/fast-export.git ~/fast-export

      - name: Clone Mercurial repo
        run: |
          hg clone https://hg.sr.ht/~snoooooooope/Dotfiles src-hg

      - name: Convert Mercurial to Git
        run: |
          git init src-git
          cd src-git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          ~/fast-export/hg-fast-export.sh -r ../src-hg
          git checkout HEAD

      - name: Copy files from src-git to root, preserve .github
        run: |
          rsync -a --exclude='.git' --exclude='.github' src-git/ ./ || [ $? -eq 24 ]
          rm -rf src-git src-hg

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git status
          git diff --cached --quiet || git commit -m "Mirror from Mercurial (via GitHub Actions)"
          git push origin HEAD
